### PR TITLE
allow PUT as api option

### PR DESCRIPTION
**Pull request by wernull**
some yahoo api options only allow put and not post (Roster resource)

On a side note, have you successfully done a post or put to the yahoo api using JSON? I added a test like the one you did for post using JSON. However, I can only get yahoo to accept XML in a post or put.

### CODE REVIEW

**Comment by jcreamer898** [comment]
Yeah, I had to use XML... it was gross, but it worked. I'll try to dig up the example I used.

**Comment by jcreamer898** [comment]
This is what I used...

I posted to...

http://fantasysports.yahooapis.com/fantasy/v2/league/331.l.198983/transactions?format=json

With this XML

``` xml
<?xml version="1.0" encoding="UTF-8" ?>
<fantasy_content>
    <transaction>
        <type>drop</type>
        <player>
            <player_key>331.p.24869</player_key>
            <transaction_data>
                <type>drop</type>
                <source_team_key>331.l.198983.t.2</source_team_key>
            </transaction_data>
        </player>
    </transaction>
</fantasy_content>
```

**Comment by jcreamer898** [comment]
Done, thanks so much!

**Comment by wernull** [comment]
Here is an example of what I ended up doing using js2xmlparser https://github.com/michaelkourlas/node-js2xmlparser

```
var js2xmlparser = require('js2xmlparser');
var changeData =  {
                roster: {
                    coverage_type: 'week',
                    week: 'current',
                    players: [
                        {
                            player: {
                                player_key: '331.p.24553',
                                position: 'BN'
                            }
                        }
                    ]
                }
            };
FantasySports.request(req, res).api(yahooRosterUrl, 'PUT', js2xmlparser('fantasy_content', changeData));
```

**Pull request merged**
